config/routes.rb
Rails.application.routes.draw do
  root :to => 'pieces#index'
  resources :users do
    resources :pieces
  end

  resources :pieces do
    resources :reviews
  end

  resources :pieces do
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_many :ratings

  validates :title, :presence => true
  validates :artist, :presence => true
  validates :created, :presence => true
  validates :image, :presence => true

  scope :sort_alpha, -> {order(title: :asc)}
  scope :sort_date, -> {order(created_at: :desc).limit(10)}

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :piece

  validates :rate, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :piece

  validates :body, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pieces

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def index
    @pieces = Piece.all
    if params[:sort] == "alpha"
      @pieces = Piece.sort_alpha
    elsif params[:sort] == "date"
        @pieces = Piece.sort_date
    else
      @pieces = Piece.all
    end
  end

  def show
    @piece = Piece.find(params[:id])
    @user = @piece.user
  end

  def new
    @user = User.find(params[:user_id])
    @piece = @user.pieces.new

    # redirect_to new_user_piece_path(@user_id)
  end

  def create
    # binding.pry
    @user = User.find(params[:user_id])
    @piece = @user.pieces.new(piece_params)

    if @piece.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @piece = Piece.find(params[:id])
    @user = @piece.user
  end

  def update
    @piece = Piece.find(params[:id])
    @user = @piece.user
    if @piece.update(piece_params)
      redirect_to user_piece_path(@user, @piece)
    else
      render :edit
    end
  end

  def destroy
    @piece = Piece.find(params[:id])
    @user = @piece.user
    @piece.destroy
    redirect_to user_path(@user)
  end

private
  def piece_params
    params.require(:piece).permit(:title, :artist, :created, :image, :genre, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pieces = @user.pieces
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>))<=>((</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <h1><%= link_to "Brian Cook's Fandemonium", root_path %></h1>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Users", users_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pieces/_form.html.erb
<%= render "layouts/errors", :object => @piece %>

<%= form_for [@user, @piece] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <%= f.label :created %>
  <%= f.date_field :created %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.submit %>
<% end %>

app/views/pieces/edit.html.erb
<h1>Edit <%= @piece.title %> </h1>
<%= render "form" %>

app/views/pieces/index.html.erb
<h1>Brian Cook Official Fan Club</h1>

<p>Click <%= link_to "here", users_path %> to post a review or rating</p>

<!-- <%= link_to "Sort Alphabeically", pieces_path(:sort => "alpha") %> -->

<!-- <%= link_to "Sort Alphabeically", pieces_path %> -->

<a href="?sort=alpha"><button class="btn">Sort Alphabetically</button></a>

<a href="?sort=date"><button class="btn">Sort by Date Work Was Created</button></a>

<ul style="list-style-type:none">
  <% @pieces.each do |piece| %>
    <li>
      <img src="<%= piece.image%>">
      <br>
      <b>Title:</b> <%= piece.title%>
      <br>
      <b>Artist:</b> <%= piece.artist%>
      <br>
      <b>Posted by User number:</b> <%= piece.user_id%>
    </li>
  <% end %>
</ul>

app/views/pieces/new.html.erb
<%= render "form" %>

app/views/pieces/show.html.erb
<h1><%= @piece.title %></h1>
<img src="<%= @piece.image %>">
<%= link_to "Edit Details", edit_user_piece_path(@user, @piece) %>

<button type="button" name="button">
<%= link_to "Delete this Piece", piece_path(@piece),
                  :data => {:confirm => "Are you sure?",
                  :method => "delete"} %></button>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>Create New User Details</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>


<ul>
  <% if @pieces.any? %>
    <% @pieces.each do |piece| %>
      <li><%= link_to piece.title, piece_path(piece) %></li>
    <% end %>
    <% else %>
      <h2><%= @user.name %> has not posted any pieces yet.</h2>
    <% end %>
</ul>

<h1>(reviews and ratings will go in this zone)</h1>

<h1><%= link_to "add a piece", new_user_piece_path(@user.id) %></h1>